"""Add columns for diacritics removal, not letters removal and reversed word detection

Revision ID: 5dd4c0425460
Revises: 
Create Date: 2025-11-25 19:26:26.598027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd4c0425460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('replace_diacritics', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('guilds', sa.Column('remove_not_letters', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('guilds', sa.Column('reversed_detection', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'reversed_detection')
    op.drop_column('guilds', 'remove_not_letters')
    op.drop_column('guilds', 'replace_diacritics')
    # ### end Alembic commands ###
