"""Add send_messages column

Revision ID: 960a27f61586
Revises: 5dd4c0425460
Create Date: 2025-11-25 21:34:22.555622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960a27f61586'
down_revision: Union[str, Sequence[str], None] = '5dd4c0425460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('send_messages', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'send_messages')
    # ### end Alembic commands ###
